<?php
$name = 'age_verification';
$value = 'true';
$period = 86400;
$cookie = Mage::getModel('core/cookie')->get($name);
if (($cookie == 0) || (!$cookie)) {
?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        var popup = jQuery('#newsletter-popup');

        jQuery('.close_popup').click(function(){
          <?php Mage::getModel('core/cookie')->set($name, 1, $period);?>
            popup.fadeOut();
        });
        jQuery('.close_redirect').click(function() {
            <?php Mage::getModel('core/cookie')->set($name, 0, $period);?>
            window.location.href = 'http://www.google.com';
        });
    });
</script>
<div id="newsletter-popup" class="container">
  <div class="sub-container">
    <!--<div class="close_popup">X</div>-->
    <div class="content">
      <div class="newsletter_content">
        <div class="display_logo"><img src="/skin/frontend/default/theme574/images/vape-hub-black-300w.png"></div>
        <div class="popup-content-right">
          <h1>AGE CERTIFICATION</h1>
          <h2>Are you of legal smoking age?</h2>
          <div class="yes-no-container">
            <div class="close_popup age-yes age-c">
              YES
              <div class="yes-info yn-info">I am of legal smoking age</div>
            </div>
            <div class="close_redirect age-no age-c">
              NO
              <div class="no-info yn-info">I am NOT of legal smoking age</div>
            </div>
          </div>
          <div class="c-bottom-info">
            <h3>The products on this website are intended for adults only.</h3>
            <span>By entering this website, you certify that you are of legal smoking age in the state in which you reside.</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php } else {
var_dump("Ryan");
  header("Location: http://www.google.com");

} ?>