<?php
$name = 'age_verification';
$cookie = Mage::getModel('core/cookie')->get($name);
if (($cookie == 'under') || (!$cookie)) {?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        
        var popup = jQuery('#newsletter-popup');

        jQuery(".btn-yes").on('click', function(e) {
            Mage.Cookies.set('age_verification', 'over');
            popup.fadeOut();
        });
        jQuery('.btn-no').on('click', function(e) {
            Mage.Cookies.set('age_verification', 'under');
            window.location.href = 'http://www.google.com';
        })
    });
</script>
<div id="newsletter-popup" class="container">
  <div class="sub-container">
    <!--<div class="close_popup">X</div>-->
    <div class="content">
      <div class="newsletter_content">
        <div class="display_logo"><img src="/skin/frontend/default/theme574/images/vape-hub-black-300w.png"></div>
        <div class="popup-content-right">
          <h1>AGE CERTIFICATION</h1>
          <h2>Are you of legal smoking age?</h2>
          <div class="yes-no-container">
              <form action="#" name="age">
                  <div class="age-box">
                      <button type="button" title="Yes Over 18" class="button btn-yes"><span>YES</span></button>
                      <button type="button" title="No Under 18" class="button btn-no"><span>NO</span></button>
                  </div>
              </form>
          <div class="c-bottom-info">
            <h3>The products on this website are intended for adults only.</h3>
            <span>By entering this website, you certify that you are of legal smoking age in the state in which you reside.</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php } else {
 // header("Location: http://www.google.com");

} ?>